name: Gallery

on: 
  repository_dispatch:
  workflow_dispatch:
  push:
    branches: master
  schedule:
    - cron: '0 16 * * *'

jobs:
  deploy:
    name: Gallery
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: master

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: "15.x"

    - name: Catch
      uses: actions/cache@v2
      id: cache-dependencies
      with:
        path: node_modules
        key: ${{runner.OS}}-${{hashFiles('**/package-lock.json')}}

    - name: Install Dependencies
      if: steps.cache-dependencies.outputs.cache-hit != 'true'
      run: |
        npm i @matrixage/picpic

    - name: Generate
      run: |
        mkdir assets
        mv -f ./blog/* ./assets/
        npm run build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'

    - name: Delete Workflow Runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 1

    - name: Telegram Notification
      if: cancelled() == false
      uses: xinthink/action-telegram@v1.1
      with:
        botToken: ${{ secrets.TG_BOT_TOKEN }}
        chatId: ${{ secrets.TG_CHAT_ID }}
        jobStatus: ${{ job.status }}
        skipSuccess: false